### ISSUE TITLE
Way to be notified there has been software update without checking website.

### ISSUE THREAD

**Issue by bob3k3** [ratgdo/homekit-ratgdo#109]
Noticed in the .11 update it states  "Automatically detect new releases on github". Not sure what this means but it would be nice to somehow be able to know when updates are released rather than having to go to the site to look. Not a big deal but just curious if it's possible or there's something I don't understand about Github.   My device is rock solid. Very impressed and appreciative. TIA

**Comment by SShah7433** [comment]
Not ratgdo specific, but you can enable notifications in GitHub for releases. To do this:

1. Navigate to the landing page for this repository: https://github.com/ratgdo/homekit-ratgdo
2. Click the **Watch** button, click **Custom**, then check **Releases**, followed by **Apply**.

You can manage how you receive these notifications in the Settings section of your account.

**Comment by bob3k3** [comment]
Thank you so much!

**Comment by dkerr64** [comment]
This should be closed.  Nothing to be done in the code.

**Comment by bob3k3** [comment]
Closed
