### ISSUE TITLE
Change Wifi SSID with Flashing Board

### ISSUE THREAD

**Issue by grouchystitch** [ratgdo/homekit-ratgdo#110]
Good Morning. Could there be an option to change the SSID / Network without having to flash the board? I am trying to segregate my IoT Devices to a different SSID and can't change the RATGDO wifi unless I flash the complete board.

thank you.

**Comment by blueyetisoftware-jason** [comment]
There is a way to access settings by visiting the IP address, but they are behind some sort of username and password. I don’t recall setting those up, so they may be defaulted in the firmware

**Comment by grouchystitch** [comment]
I can access the device via the web with the IP Address but there is no option to change WIFI settings.

**Comment by dkerr64** [comment]
How strongly do people feel about this?  I could add it to the settings page,

**Comment by grouchystitch** [comment]
> How strongly do people feel about this? I could add it to the settings page,

It would be amazing if possible . Thank you for your amazing work and support.

**Comment by dkerr64** [comment]
> > How strongly do people feel about this? I could add it to the settings page,
> 
> It would be amazing if possible . Thank you for your amazing work and support.

The user interface side is easy enough now that I have settings page.  I need to find out where the SSID/password are stored though.

**Comment by mitchjs** [comment]
its done by a sevice called INPROV
the webpage you loaded the firmware.. .you connect to the board... and you should be able to change wifi

**Comment by dkerr64** [comment]
> its done by a sevice called INPROV the webpage you loaded the firmware.. .you connect to the board... and you should be able to change wifi

The problem is that this requires connecting the ratgdo board to a computer with USB cable.  Once installed at the GDO it is kind of awkward to have to go out to the garage with your laptop and a long USB cable... or to disconnect the ratgdo and bring it inside to flash.

While likely rare, I can see the need to be able to update WiFi settings without having to connect to USB... ie, from a web browser.

**Comment by mitchjs** [comment]
thats true... maybe we can put it in the web, course one makes a mistake... it prob needs to timeout.. maybe it can default back
else then one would need the USB cable

**Comment by jgstroud** [comment]
Don't think we will implement this in the webUI, but you can do this using Improv by vising the web flash page in chrome.  You need to be connected to the device over USB.
https://ratgdo.github.io/homekit-ratgdo/flash.html
