### ISSUE TITLE
Recover or reset password

### ISSUE THREAD

**Issue by Landonthi** [ratgdo/homekit-ratgdo#112]
Wondering if there is a way to reset or recover the password for my RATGDO that is setup to HomeKit. I don't remember setting a password for the device. Im unable to get into the settings or use any of the commands on the device webpage. Any help would be greatly appreciated. Thanks

**Comment by DesertHillsautomation** [comment]
I am in the same boat looking for a password I never set up to the IP address of the board for HomeKit. When I click on the gear icon on the HomeKit IP page for the board, it asks me for a user name and password.

**Comment by idarrenly** [comment]
Username/password implemented in v0.11.0. 

Release notes says default username/password is admin/password

**Comment by DesertHillsautomation** [comment]
That worked. Appreciate the info.

**Comment by Landonthi** [comment]
Thanks for the info! This worked for me too. Appreciate it.

**Comment by dkerr64** [comment]
We need to update the readme.  And/or allow for no authentication required, and make that the default.

**Comment by dkerr64** [comment]
Pull request #113 (and #117... they are identical) provides for the web password to be optional and displays the default (admin/password) on the settings page.

First time this is run the default is to NOT require a password, user has to go into settings and enable it.  Thoughts as to whether that is the correct default?
