### ISSUE TITLE
QUESTION: How to pair?

### ISSUE THREAD

**Issue by russellquinn** [ratgdo/homekit-ratgdo#121]
I have flashed my new RATGDO with homekit-ratgdo. I can access the web interface. But, when I tap on "Pair to HomeKit" I get "Pair to new HomeKit, are you sure?" but when clicking OK it just downloads a zero kb file named Reset.

I've tried this on Safari and Chrome on macOS and in Safari on iOS (all devices connected to HomeKit) and get the same thing.

I tried scanning the QR Code from the Home app instead, and this did successfully add Door and Light to HomeKit but they are both immediately non-responsive. Furthermore, the homekit-ratgdo web interface still shows the QR code and "Pair to HomeKit," which from reading the documentation means it doesn't think it's paired.

The buttons in the homekit-ratgdo web interface work fine.

So, my question, what is "Pair to HomeKit" supposed to do? What's going wrong in my flow?

Thanks!

Russell

**Comment by jgstroud** [comment]
The problem with it downloading an empty reset file is a bug and will be fixed in the next release.  

It sounds like your pairing failed in some way.  Try removing the device from HomeKit, rebooting the ratgdo and repair it using the QR code.

**Comment by russellquinn** [comment]
Thanks for the note. I couldn't get it to pair at all and I tried multiple methods. I ended up reflashing with MQTT and connecting via Homebridge.

**Comment by jgstroud** [comment]
@russellquinn would you be willing to test this bug using the latest firmware?

**Comment by russellquinn** [comment]
Sorry, I went with MGTT and Homebridge now, which has been super stable for me, so I don't want to switch firmware flavors again.
