### ISSUE TITLE
I am never asked for my password

### ISSUE THREAD

**Issue by Dot-Dash** [ratgdo/homekit-ratgdo#138]
I have added and saved a password and checked "require password", yet I have never been asked for my password. I can connect and control the GDO with no attempt at authentication.  

I am currently on version 1.1.0, but have been seeing this issue in the last few versions. I have never had any version ask for the password.

**Comment by dkerr64** [comment]
Your browser has probably cached it.  Try changing the password and see if you are prompted for it then.

**Comment by Dot-Dash** [comment]
I had gone through the steps to change the password many times, but always with the same password. Just now, I tried changing it to something different, and then was prompted to login when I tried to turn on the light.

**Comment by dkerr64** [comment]
Yes, that is expected behavior.  I do not know how long it is remembered, it could vary by browser.
