### ISSUE TITLE
Every command writes to EEPROM

### ISSUE THREAD

**Issue by thenewwazoo** [ratgdo/homekit-ratgdo#14]
Every time a command is sent, the rolling code value is written to EEPROM. This is not ideal, as (very, very, very) frequent usage could result in the EEPROM exceeding its rated write cycles (100k?).

Refactor the code to:
* only write the rolling code count to EEPROM once every _n_ commands
* Increment the stored count by _n_ at boot up

This will reduce flash wear by a factor of _n_, and extend hardware life.

**Comment by kala-ghoda** [comment]
Hi, I am starting with open-source contribution and would like to try and help with this. Could you please assign me this issue?

**Comment by thenewwazoo** [comment]
@kala-ghoda I appreciate your willingness to contribute, but I learned today that LittleFS, which my firmware uses, does automatic wear levelling, and so this feature isn't necessary. If you want to try fixing another bug or adding another feature, you don't need to wait for me to assign the issue (I won't, anyway)... just submit a PR at your convenience. :)
