### ISSUE TITLE
Motion sensor not reliably included in "group"

### ISSUE THREAD

**Issue by jtouch** [ratgdo/homekit-ratgdo#157]
Two identical openers and wall switches with motion sensors. One adds three items (motion, door, light), one only two (door, light). Tried reflashing and adding them in different orders, with one always showing up without the motion sensor.

Firmware v1.2.1

**Comment by donavanbecker** [comment]
If motion isn't tripped then the sensor doesn't show.

**Comment by jtouch** [comment]
OK - thanks; it shows now. Under homebridge, the devices are always added as all three components, regardless of activity. In native homekit, the motion sensor was added later - not at the time of pairing.

**Comment by jgstroud** [comment]
It was implemented this way so that it would only show up for users that have a motion sensor.
