### ISSUE TITLE
Security+ 1.0 state not syncing

### ISSUE THREAD

**Issue by crockpotveggies** [ratgdo/homekit-ratgdo#159]
Purple square learn button. Ran MQTT firmware for 3 months stable. Switched to HomeKit firmware. Haven't rewired.

After switching door protocol in settings, the only function I'm able to perform is close the garage door. However the state remains on. Additionally, the light switch is not updating and remains off and I'm unable to control it.

Edit: strangely when I leave it alone, it still thinks the Garage is open and when I try to close it, it then opens the already closed garage door.

I don't see any prompts to view logs, so I assume there's no crash? How do I debug this?

<img width="787" alt="Screenshot 2024-04-23 at 5 27 21 PM" src="https://github.com/ratgdo/homekit-ratgdo/assets/1445295/6f8b111d-9c68-42f3-865b-e10e631c58fb">

![IMG_4567](https://github.com/ratgdo/homekit-ratgdo/assets/1445295/d9c2f7f6-1b7c-4a25-83d9-af46e962988d)

**Comment by jgstroud** [comment]
So this is a security+ 1.0 door.  maybe @mitchjs knows what might be going on?

**Comment by jgstroud** [comment]
Also, in the current build, the logs are only available in the serial console.

**Comment by crockpotveggies** [comment]
@jgstroud is there a link or wiki page that describes how to set up the serial console?

**Comment by mitchjs** [comment]
@crockpotveggies, Do you have a wall panel?
if not it has to go in to emulation mode.... not as well tested, as 99% of the people got a wall panel
(and not a plain old push button)

**Comment by 100ideas** [comment]
Just shared my similar issues with console logs over at https://github.com/ratgdo/homekit-ratgdo/issues/132#issuecomment-2165326762

**Comment by mitchjs** [comment]
good news, i found the issue (my fault)... i will fix with a PR soon

**Comment by dkerr64** [comment]
Fixed in version 1.6.1
