### ISSUE TITLE
Make obstruction detection use the wire instead of the status bit

### ISSUE THREAD

**Issue by thenewwazoo** [ratgdo/homekit-ratgdo#16]
Obstruction support is not completely implemented. The characteristic is required so it's already there, and its value is based on the status packet bit, but that bit is not like super reliable.

Add code for reading and reporting the state of the obstruction sensor wire itself, and updating the characteristic with that value. Probably ignore the status packet bit, or at least confer with the other firmware authors to figure out how it works (or doesn't).

**Comment by jgstroud** [comment]
https://github.com/ratgdo/homekit-ratgdo/pull/40

**Comment by thenewwazoo** [comment]
Fixed in #40
