### ISSUE TITLE
Some Praise & Thanks!!

### ISSUE THREAD

**Issue by infamous-pattern** [ratgdo/homekit-ratgdo#179]
Sorry, no issue here. Just some well deserved praise for all the work you do on this project. I'm blown away at how quickly things have progressed and have been resolved. You're all amazing!

Thank you.
![cheers](https://github.com/ratgdo/homekit-ratgdo/assets/79342196/3fd0e797-dfb3-4374-9625-75ec30240d01)

**Comment by cefoster0** [comment]
Agreed, thank you!

**Comment by dewaniuk** [comment]
Seconded!!! Thank you!

**Comment by rlowens** [comment]
> well deserved praise

[closed as not planned]

:)

**Comment by jgstroud** [comment]
Thanks to @dkerr64 for all his hard work on these releases.
