### ISSUE TITLE
Closed Notifications Not Working.

### ISSUE THREAD

**Issue by JEMcats** [ratgdo/homekit-ratgdo#199]
I recently got the RATGDO and it works almost perfectly but, even though i receive notifications for when the garage door is opened, i don't get notifications when it is closed even though if i look in homekit after the event, the garage door is shown as closed. Please Help.
<img width="160" alt="Screenshot 2024-06-06 at 3 23 51 PM" src="https://github.com/ratgdo/homekit-ratgdo/assets/67199328/f8fba57e-ff14-4359-b797-5f40d95eaac9">
<img width="500" alt="Screenshot 2024-06-06 at 3 23 28 PM" src="https://github.com/ratgdo/homekit-ratgdo/assets/67199328/8d5860e5-28b7-4a1b-8eb6-b652adf2b5d3">

**Comment by jgstroud** [comment]
Fixed in #204
