### ISSUE TITLE
Since 1.5 update - web interface works but no Home kit integration 

### ISSUE THREAD

**Issue by sebastiangoldstein** [ratgdo/homekit-ratgdo#201]
Since the update to 1.5 garage doors show as unresponsive in Home Hit. The Website can control the door but the home kit cannot.
Secutity+ setup

**Comment by dkerr64** [comment]
On the webpage please click the reset / re-pair HomeKit button.  In Apple Home please delete the garage door accessory, stop and restart Apple Home, and then re-pair the device (scan QR code again).  Pairing can take a few minutes.

Unfortunately, a bug-fix we had to include in 1.5.0 was related to HomeKit pairing and requires the above steps.

**Comment by sebastiangoldstein** [comment]
Thank you - Followed the above steps - Back in business.
