### ISSUE TITLE
v1.5.0 shows temporary incorrect transition status when closing

### ISSUE THREAD

**Issue by jtouch** [ratgdo/homekit-ratgdo#203]
Starting from the OPEN state and clicking in HomeKit to close the door:

the door shows "closing..." then changes to "opening..." (even though the door continues to close).

when the door finishes opening, the tile goes from white to grey, but still says "opening..." for a fairly long time until it finally transitions to "closed".

**Comment by jgstroud** [comment]
I was able to reproduce this odd behavior using my wall panel button.  Someone mentioned something similar on discord.  But the logs appear to be sending the correct data.

**Comment by jgstroud** [comment]
Fixed in #204.   will do a release build tomorrow.
