### ISSUE TITLE
Make LED polarity configurable

### ISSUE THREAD

**Issue by jgstroud** [ratgdo/homekit-ratgdo#221]
Some users really don't like having the LED on all the time.  I personally like seeing it on to indicate it's alive and well.  We can make the polarity configurable and optionally only allow it to be on when motion is detected in the garage.  The LED may also attract bugs in some environments.

**Comment by jgstroud** [comment]
Well, it already blinks on activity on the serial link.  I think we leave that part as is.

**Comment by dkerr64** [comment]
So, you propose an option that essentially inverts current behavior... so if users prefer the light to be mostly off they can have that.

**Comment by jgstroud** [comment]
Yeah, I think that's the easiest solution without overcomplicating anything.  But I don't really have a strong opinion about it.  Ever since it was implemented, it seems like we get about 50/50 feedback on users that would prefer it mostly on vs those that would prefer it mostly off.

**Comment by dkerr64** [comment]
I've figured out how to implement so I will code it up tonight and see how well it works.

**Comment by dkerr64** [comment]
Implemented in PR #220

**Comment by dkerr64** [comment]
Implemented in v1.7
