### ISSUE TITLE
Flasher page log doesn't work

### ISSUE THREAD

**Issue by thenewwazoo** [ratgdo/homekit-ratgdo#23]
The device log in the [flasher page](https://ratgdo.github.io/homekit-ratgdo/flash.html) doesn't work. No idea why. It'll speak Improv so obviously it's getting serial bytes but... just nothing shows up. Super weird.

**Comment by PaulWieland** [comment]
Open the logs then click reset device. Sometimes the logs will not refresh if the device has already been running for a while.

<img width="1161" alt="image" src="https://github.com/ratgdo/homekit-ratgdo/assets/4663918/4d6fc0db-319c-4621-a700-165745b60ee2">

**Comment by thenewwazoo** [comment]
Huh. That's super weird. I can't find any reason it wouldn't just work all the time. I have an open issue in the esp-web-tools repo to see if maybe I can get some eyes on it.

**Comment by jgstroud** [comment]
Logs seem to be working.
