### ISSUE TITLE
Door Unlocked Notification

### ISSUE THREAD

**Issue by djducat** [ratgdo/homekit-ratgdo#233]
Twice now, Homekit has reported that my garage door was unlocked.  I have no automation around locking and unlocking the door, it's not a feature I even use.  I am not getting any "locked" notifications, just "unlocked".  Is this a bug?

**Comment by jgstroud** [comment]
It's probably a bug.  We would need to see the logs when it happens to see what triggered the update.

**Comment by djducat** [comment]
next time it happens, I'll grab the logs.  is there a URL for the log?

**Comment by dkerr64** [comment]
There is a [script file](https://github.com/ratgdo/homekit-ratgdo/blob/main/viewlog.sh) that you can run on Linux or Mac that will dump the current log and remain connected and report new messages as they occur.  However you would have to leave this running to have any chance of catching the logs as we have very limited memory in which to save past messages.

**Comment by dkerr64** [comment]
Believed to be fixed in release 1.8.0
