### ISSUE TITLE
Feature Request: Automatic UI Theme

### ISSUE THREAD

**Issue by donavanbecker** [ratgdo/homekit-ratgdo#240]
Would be nice if there was a light and dark theme for the UI that would follow device settings and would switch between light and dark based on the device's settings.

**Comment by dkerr64** [comment]
We have that already. Or at least we did, maybe I broke it. But I only tested on MacOS and iOS devices. You will have to reload the page if you change theme on your device.

**Comment by donavanbecker** [comment]
Nevermind it wasn't working for me and now it is.
