### ISSUE TITLE
Feature Request: Disable LED blinking.

### ISSUE THREAD

**Issue by JKaniarz** [ratgdo/homekit-ratgdo#248]
Could I trouble you for an option to make the LED always on or off? My preference is for always on, but whatever is easiest works. Both current activity settings cause a lot of blinking that's disorienting when the garage is otherwise dark.

**Comment by jgstroud** [comment]
You could just put a piece of tape over it

**Comment by clindst** [comment]
@JKaniarz Does yours blink constantly like the video I've attached?  Mine does and it drives me crazy even after disabling the "LED on when idle" setting.  Sure, I could put tape over it but it seems like this should be a simple setting. 

I'm not sure this matters but I'm running this on a Sec+ Door protocol.

https://github.com/user-attachments/assets/0ed37545-1ed4-4494-9a00-995574082adf

**Comment by JKaniarz** [comment]
I see the same nonstop blinking. Mine is also Sec+.

**Comment by dkerr64** [comment]
The LED is supposed to flash when there is activity on the comms link from ratgdo to the door opener.  On my (Sec+ 2.0) it is not unreasonably active.  If I go into my garage and the motion detector senses me, then it gets more active.

However, that said, I am not against adding a control to turn it off.  I'm kind of busy, but will add to to-do for next update.

Thanks.

**Comment by PaulWieland** [comment]
The problem is that security + 1.0 is a constant stream of serial communication with the opener, so the led just flashes constantly. To me, the best would be to have the led flash when it receives a network request. This can help verify that network communication is working when trouble shooting.

**Comment by dkerr64** [comment]
Added in PR #247 so will be in next release whenever we do that.

**Comment by JKaniarz** [comment]
Thank you!

**Comment by dkerr64** [comment]
Implemented in 1.8.2
