### ISSUE TITLE
Set activity LED off unless there is activity

### ISSUE THREAD

**Issue by adrianradtke** [ratgdo/homekit-ratgdo#25]
LED stays on with current version. Set LED to default off unless there is activity (ie command sent from HomeKit, door in operation)

**Comment by PaulWieland** [comment]
fwiw, the mqtt firmware turns the led on when searching for wifi. Once connected it shuts off. It then flashes whenever it receives a command.

**Comment by thenewwazoo** [comment]
Fixed in #43
