### ISSUE TITLE
Homekit Automation shows Lock / Unlock vs Open / Close - 2nd Garage Door RatGDO

### ISSUE THREAD

**Issue by spatick1** [ratgdo/homekit-ratgdo#255]
I have 2 garage doors (Double Door and Single Door) and installed RatGDO on both and added them to Homekit.  I'm adding some automation to turn the lights on / off with the doors opening / closing.  One of the doors is as it should be when I add an automation and the door shows up with open and close.  The other door (screenshot attached) shows only Locks and Unlocks.  I have no locks on either door - just open / close / light.  I have done a HomeKit unpair / repair and that did not change anything.

Lemme know if there's any advice!!

![IMG_7032](https://github.com/user-attachments/assets/c8ac7c9a-d0c1-4f1c-835b-52329f7cec76)

**Comment by donavanbecker** [comment]
This is a HomeKit bug, you will need to setup in a 3rd party app.

**Comment by spatick1** [comment]
Thx!  Is there a recommended 3rd party app?  I'm using Homekit for mostly everything now.

**Comment by donavanbecker** [comment]
Eve or Controller for HomeKit.

You can make the automation in HomeKit by using one of these apps.

Then when you look at the automation in the Home app you will see it set up under opened/closed.

**Comment by spatick1** [comment]
Thank you!  Worked perfectly. PATOn Dec 8, 2024, at 8:02 PM, Donavan Becker ***@***.***> wrote:﻿
Eve or Controller for HomeKit.
You can make the automation in HomeKit by using one of these apps.
Then when you look at the automation in the Home app you will see it set up under opened/closed.
