### ISSUE TITLE
Inconsistent HomeKit Connectivity 1.8.3

### ISSUE THREAD

**Issue by dfree2350** [ratgdo/homekit-ratgdo#257]
After 1.8.3 and 18.2 OS my HomeKit will mark each of my door openers as No Response, usually regain connection, then drop again. Device is connected to network as I can reach it via IP.

**Comment by dkerr64** [comment]
I have updated my Apple devices to 18.2 and I do not see any problems.  Hopefully what you are seeing is only temporary.

**Comment by jgstroud** [comment]
I'm also running this firmware combo and I verified my HomePod is also running 18.2.  Devices going unresponsive usually indicates an mdns problem.  If you run the Discovery app, do you see the ratgdo?  Are your devices on the same subnet / vlan?  Are you running homebridge with BonjourHAP?

**Comment by dfree2350** [comment]
I did full resets a couple days ago. and that must’ve gotten it. They’ve been on since then without issues.
