### ISSUE TITLE
HA not finding Ratgdo MQTT

### ISSUE THREAD

**Issue by mrwkbrdr** [ratgdo/homekit-ratgdo#28]
For some reason my HA is not detecting my ratgdo. My HA is reporting other MQTT devices?
My MQTT broker can see it? 
Any suggestions?

HA:
Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.1
Frontend
202310.2

MQTT broker:

shellyplugus-
shellyplugus-
frigate
homeassistant
cover
light
binary_sensor
MAIN DOORGARAGE DOOR
status
availability = online
obstruction = clear
motion = detected
door = closed
light = on
lock = unlocked
$SYS
shellies

**Comment by thenewwazoo** [comment]
This repo is for the homekit-only firmware and does not interface with homeassistant.
