### ISSUE TITLE
Internet access required to retrieve QR code

### ISSUE THREAD

**Issue by dkerr64** [ratgdo/homekit-ratgdo#42]
The pairing QR code should be self contained within the device.  Right now [internet access is required](https://github.com/ratgdo/homekit-ratgdo/blob/76859d4ad78d5918b44a8686a57094927dbd2f47/src/web.cpp#L55) to retrieve the QR code and is therefore at risk of not being available.

Need to find a way to embed this with the firmware and not require internet access.

**Comment by thenewwazoo** [comment]
Given that flashing the device requires internet connectivity, I don't think storing the QR code in the device's flash (or the code necessary to generate a QR code on-demand) is worth the EEPROM cost, especially when I'm hoping to (eventually) shrink it small enough to permit OTA updates.
