### ISSUE TITLE
Smart Wall Button permanently shows Sensor Obstructed and won't clear.

### ISSUE THREAD

**Issue by V025** [ratgdo/homekit-ratgdo#47]
I'm running ratGDO v2.5 HW,  homekit-ratgdo-v0.6.0 FW,  LiftMaster 8550WL.
I have the fancy 880LMW Wall Button with motion sensor and the LCD display on it constantly displays:

SENSOR MOMENTARILY
OBSTRUCTED
ERROR CODE 4-6
SEE USER MANUAL

The top GDO button works, and the bottom light button works, but nothing I can do to clear the message... the 4 menu function buttons directly under the LCD don't do anything to clear the screen either.   I still have the MyQ app installed and the MyQ Diagnostics show No Issue(s) reported, and it shows that the sensors are good and aligned (meaning no obstruction I guess).  Unplugging Liftmaster and replugging didn't fix either.

(Just received ratGDO HW, loaded v0.6.0 HK FW,, and wired up.  Everything works beautifully and I just spent the last half hour testing everything I could think of on homekit/etc as well as sensors/lights/buttons.  All works well with only this one bug found thus far- Thanks for everyone's fun hard work!!! )
![IMG_6224](https://github.com/ratgdo/homekit-ratgdo/assets/107151610/25e5468e-d7e1-4cab-869b-508cd79a16d6)
![IMG_6225](https://github.com/ratgdo/homekit-ratgdo/assets/107151610/37fadcdf-700f-4f41-8b70-b9ee2c8e868b)

**Comment by reh8388** [comment]
I have the same controls and the screen lock up over time and have odd behaviors. Try rebooting the wall controls by disconnecting one of the wires to it and reconnecting to see if that solves your problem.

**Comment by thenewwazoo** [comment]
Unfortunately I can’t personally reproduce the issue, but this seems to me most likely to be a wiring issue, since the obstruction sensor(s) are wired separately.
