### ISSUE TITLE
Discord link on project page is broken 

### ISSUE THREAD

**Issue by klische** [ratgdo/homekit-ratgdo#59]
The discord link on the project home page  https://github.com/ratgdo/homekit-ratgdo/blob/2b590057b7081276f0b00bce471a3109112a5aca/README.md?plain=1#L77

Pointing to https://discord.com/channels/432663330281226270/1184710180563329115 is broken. It should be an invite to the Discord server, so tapping/clicking on it will launch the Discord app or website and take you directly to the project’s Discord. Invites should look like https://discord.gg/hTKzmak, hTKzmak, or https://discord.gg/cool-people

**Comment by thenewwazoo** [comment]
Thanks! I was just trying to figure this out last night. Can you confirm that this link works?

https://discord.gg/homebridge-432663330281226270

**Comment by eightnoneone** [comment]
Worked for me.

**Comment by klische** [comment]
Works! Thanks! There are 3 ratgdo channels though. Which is which? https://discord.com/channels/432663330281226270/1184710180563329115

https://discord.com/channels/432663330281226270/1178451927550394368

The above also has 2 threads, one of which is actively being commented in. An explanation of what channel is for what topics would be useful, but we can mark this closed for now.

**Comment by donavanbecker** [comment]
> https://discord.com/channels/432663330281226270/1184710180563329115

This one is for native HomeKit firmware as the description of the channel states:
![image](https://github.com/ratgdo/homekit-ratgdo/assets/9875439/7d84906f-a52f-41aa-a071-79374c1f868a)
