### ISSUE TITLE
obstruction and GDO light

### ISSUE THREAD

**Issue by vehlajatt** [ratgdo/homekit-ratgdo#62]
Reboot required after obstruction and GDO light stays on all the time unless manually turned off from homekit.

**Comment by thenewwazoo** [comment]
Can you please add more information here, such as a more-complete description of the issue and logs, that might help with diagnosis? I haven't seen other users report this problem.

**Comment by jgstroud** [comment]
Closing since it has been weeks without an update.  I just verified that these functions are working properly.  commenter should check their wiring.
