### ISSUE TITLE
GDO clicker remotes take multiple tries now

### ISSUE THREAD

**Issue by V025** [ratgdo/homekit-ratgdo#66]
Noticed that our car’s programmable HomeLink GDO buttons now take multiple tries… I dismissed as RF interference for a while.  Today I realized my clickers also take multiple tries to successfully send an open/close signal (My GDO is SEC+ 2.0).
HK app will always work still though, and also wired Wall button.  It’s only the clicker remotes, HomeLink, and external wireless keypad that now take multiple tries.

**Comment by rlowens** [comment]
How are you powering the ratgdo? Others have reported this problem if they wired the ratgdo to their GDO's internal 3.3V line (presumably lowering the reception power on the GDO's wireless receiver).

**Comment by PaulWieland** [comment]
Move ratgdo away from the GDO’s antennas.
