### ISSUE TITLE
Release Process Failing

### ISSUE THREAD

**Issue by donavanbecker** [ratgdo/homekit-ratgdo#68]
@PaulWieland anyway you can set the permissions outlined in this answer so that we can get the releases automated?

https://stackoverflow.com/questions/75995802/resource-not-accessible-by-integration-github-action-fails-for-pushed-commit

**Comment by donavanbecker** [comment]
@thenewwazoo Once @PaulWieland has changed the permissions you should be able to go tot he failed action and just restart the failed action.

**Comment by thenewwazoo** [comment]
Re-running it didn't succeed. I haven't taken the time to diagnose yet, sorry.

**Comment by PaulWieland** [comment]
Actually that is the global security setting and it is not changable as the option is disabled.
<img width="772" alt="image" src="https://github.com/ratgdo/homekit-ratgdo/assets/4663918/0b365bad-0c0a-4919-a4c0-eb167c4062a2">

I think the permissions have to be set at a more granular level in the workflow configuration.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

**Comment by donavanbecker** [comment]
Do you have this set?

https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#setting-the-permissions-of-the-github_token-for-your-organization

**Comment by donavanbecker** [comment]
I know as part of the Homebridge organization we have it set as an org and on the homebridge-config-ui-x for read and write and this action works:
<img width="972" alt="Screenshot 2024-01-01 at 9 42 09 AM" src="https://github.com/ratgdo/homekit-ratgdo/assets/9875439/f6fa2bab-0557-4f8d-896e-7c25b639009f">

**Comment by donavanbecker** [comment]
@thenewwazoo wanna try #69

**Comment by donavanbecker** [comment]
That didn't work @PaulWieland. So I think you will need to check these settings. I was able to get these releases to work on my fork.

**Comment by donavanbecker** [comment]
@PaulWieland just tried another one with #70 and still same issues. You will need to set these at an organization level and then it should be available at a repo level.

**Comment by donavanbecker** [comment]
#71 should resolve all of this.
