### ISSUE TITLE
Lock and Unlock exposed to HomeKit, but not Open and Close

### ISSUE THREAD

**Issue by mikemormino** [ratgdo/homekit-ratgdo#88]
When attempting to create an automation related to the door opening, Open/Close isn’t available but Lock/Unlock are.  They don’t work the same way.  Version 0.9.0.
![IMG_1415](https://github.com/ratgdo/homekit-ratgdo/assets/79295906/11fdfc38-194f-4e36-87b8-9dc2abdf69ad)

**Comment by HughesAndrewC** [comment]
I had the exact same problem. I was able to use a suggestion to get access to the door opening/closing as a trigger. 
![image](https://github.com/ratgdo/homekit-ratgdo/assets/15352765/d763daf8-207e-4fcd-b9e8-24e40869d90d)

What's interesting is that now that I have created an automation using that suggestion, I no longer have access to the lock/unlock triggers.
![image](https://github.com/ratgdo/homekit-ratgdo/assets/15352765/4cf1488f-893e-4b43-ab32-810a97b76bd0)

**Comment by mikemormino** [comment]
Yup, that worked for me too.  Interesting workaround.  Basically, the solution is to take the HomeKit suggestion and slice it and dice it to your needs.

**Comment by HughesAndrewC** [comment]
That leads me to believe it's a problem on the HomeKit side instead of the ratgdo firmware end. Is open/close now available when creating an automation from scratch?

**Comment by mikemormino** [comment]
No, just lock and unlock.

**Comment by thenewwazoo** [comment]
This is super weird and strikes me as an iOS Home app problem. I actually can't repro on the macOS version:

<img width="513" alt="image" src="https://github.com/ratgdo/homekit-ratgdo/assets/1624746/74796f29-984a-4689-8a38-e6e029d5b4ff">

It offers me the open/close trigger straight away (I have no other automations for the accessory set).

**Comment by thenewwazoo** [comment]
Going to close this as a bug in the iOS Home app and not the firmware. I'd say I'll file a RADAR but... 🤣
