### ISSUE TITLE
Add function buttons to rated web page?

### ISSUE THREAD

**Issue by strlng** [ratgdo/homekit-ratgdo#93]
Would it be possible to add buttons to trigger the door and/or lights to the ratgdo's web page? Then one could test to make sure things are wired up properly even before pairing to HomeKit.

**Comment by ChesterXLewis** [comment]
My only concern with this is then protecting this page from being accessed by others on that (Wi-Fi) network.

**Comment by thenewwazoo** [comment]
This feature would be included in the discussion #87

**Comment by dkerr64** [comment]
Please see #87.  I have this implemented and am in process of adding authentication.
