### ISSUE TITLE
Not Reporting/Controlling  in Homekit (Security + 1.0)

### ISSUE THREAD

**Issue by sebastiangoldstein** [ratgdo/homekit-ratgdo#95]
Hello,
New user - I just hooked up RatGDO which I flashed with HomeKit according to the instructions.
I have a purple Learn Button so I assume that I have a Security + 1.0
I also have the LiftMaster 889LMMC Control panel
Followed all wiring and setup instructions.
The web interface displays the correct status. 
However, adding to HomeKit displays the garage door with incorrect status and no ability to control it. 
Will post pics below 
Can someone point me in the correct direction to resolve the issue? 
Thanks:
![IMG_0734](https://github.com/ratgdo/homekit-ratgdo/assets/65564693/9f1b9532-b85f-4cb1-b3e6-90e304cbe75c)
![IMG_0737](https://github.com/ratgdo/homekit-ratgdo/assets/65564693/c0ba488e-0c09-44fd-904b-8f006e291d0e)
![Screenshot 2024-01-16 at 10 42 18 PM](https://github.com/ratgdo/homekit-ratgdo/assets/65564693/64387e10-6749-4d8c-b208-be20de962a64)
![IMG_0560](https://github.com/ratgdo/homekit-ratgdo/assets/65564693/76888053-3e1b-450b-b370-e0dc5d3572e6)

**Comment by donavanbecker** [comment]
See #46

**Comment by thenewwazoo** [comment]
Closing as dupe.
